spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cafe
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug